//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тестовое_задание.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int IdProduct { get; set; }
        public string ProdName { get; set; }
        public int ProdType { get; set; }
        public int Status { get; set; }
        public System.DateTime StatChanged { get; set; }
        public int Quantity { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual TypesOfProd TypesOfProd { get; set; }
    }
}
